spring.application.name=relatos-seguranca-api

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb

# Usuário e senha
spring.datasource.username=sa
spring.datasource.password=

# Driver
spring.datasource.driver-class-name=org.h2.Driver

# Dialeto JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criação automática das tabelas
spring.jpa.hibernate.ddl-auto=update

# Exibir SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Acesso ao console do H2
#http://localhost:8080/h2-console

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC